# [nfs]
# <NFS-Server-Private-IP-Address> ansible_ssh_user='ec2-user'

[webservers]
 172.31.93.44 ansible_ssh_user='ec2-user'
 172.31.81.168 ansible_ssh_user='ec2-user'

# [db]
# <Database-Private-IP-Address> ansible_ssh_user='ec2-user' 

# [lb]
# <Load-Balancer-Private-IP-Address> ansible_ssh_user='ubuntu'